### ISSUE TITLE
Tool very slow and blocking with using 2+ layers

### ISSUE THREAD

**Issue by yanntanvez** [energy-data/market-opportunities#22]
![image](https://cloud.githubusercontent.com/assets/21108014/19321483/2dbe3ace-9083-11e6-8aec-4a0608e6792b.png)

**Comment by drewbo** [comment]
@yanntanvez what browser and operating system are you using?

**Comment by yanntanvez** [comment]
![image](https://cloud.githubusercontent.com/assets/21108014/19322315/8af13c52-9086-11e6-92f3-2dd4f1c82ffd.png)

**Comment by yanntanvez** [comment]
![image](https://cloud.githubusercontent.com/assets/21108014/19322347/a2b045e0-9086-11e6-91bf-82e65818c9c8.png)

**Comment by drewbo** [comment]
@yanntanvez can you try recreating on https://energy-data.github.io/market-opportunities to see if the problem is mitigated? Thanks

**Comment by yanntanvez** [comment]
Hi @drewbo and thanks, I have tried this morning but encountered another error while doing so... 

@drewbo @olafveerman I think it will be important for the team to have a full review of the tool to ensure it is working well. We are finding new error each time that we open the tool at the moment... We cannot launch the tool in such conditions.

**Comment by drewbo** [comment]
@yanntanvez what was the new error? In general these errors were mostly due to migration of the service over to the new github/mapbox account and I don't expect that they will persist
