### ISSUE TITLE
Solar potential and Pop density units

### ISSUE THREAD

**Issue by yanntanvez** [energy-data/market-opportunities#34]
![image](https://cloud.githubusercontent.com/assets/21108014/19647982/92149910-99ce-11e6-9195-ecd337fff950.png)

**Comment by yanntanvez** [comment]
![image](https://cloud.githubusercontent.com/assets/21108014/19809973/9d61bc48-9cf9-11e6-88e0-42f12c0bc263.png)

**Comment by drewbo** [comment]
Closed via #49
