### ISSUE TITLE
Buffer for healthcare facilities

### ISSUE THREAD

**Issue by yanntanvez** [energy-data/market-opportunities#35]
Should start at 1km, like for the education facilities.
Thanks,
-Yann

![image](https://cloud.githubusercontent.com/assets/21108014/19699745/85dc4004-9ac2-11e6-9427-b874f19a2caf.png)

**Comment by drewbo** [comment]
@yanntanvez was this on a new session (does it show up like this when refreshing)? By default I see that both show up at 1km

**Comment by olafveerman** [comment]
This was a small glitch in the meta-data that affected the label. I've updated the metadata on the platform from:

```
"range": [5, 100]
```

to 

```
"range": [1, 100]
```

Closing this as fixed.
