### ISSUE TITLE
"Mining site" name

### ISSUE THREAD

**Issue by yanntanvez** [energy-data/market-opportunities#38]
With small i at M_i_nining.
Thanks

![image](https://cloud.githubusercontent.com/assets/21108014/19809717/7e4e1870-9cf8-11e6-9a68-9a47d2768102.png)

**Comment by olafveerman** [comment]
The first `i` is in fact lowercase:

![image](https://cloud.githubusercontent.com/assets/751330/20019976/32621c4c-a2a5-11e6-9b16-7e4d95868577.png)

This might be a Windows issue where the `i` is not rendering very cleanly on some machines.

**Comment by yanntanvez** [comment]
Appears to still be some issue with this:
![image](https://cloud.githubusercontent.com/assets/21108014/20184325/520b9dc6-a736-11e6-9d94-dea11a9d0182.png)
