### ISSUE TITLE
Indicators missing in additional countries?

### ISSUE THREAD

**Issue by yanntanvez** [energy-data/market-opportunities#42]
![image](https://cloud.githubusercontent.com/assets/21108014/20012161/7e89813a-a284-11e6-8064-812d63c10aa9.png)

![image](https://cloud.githubusercontent.com/assets/21108014/20012170/89d81b6e-a284-11e6-850d-559ed6e44931.png)

**Comment by olafveerman** [comment]
The `solar potential` and `proximity to road` are only available in the three focus countries.

`Mining sites` is available on a continental level, but doesn't have sites in Benin.
