### ISSUE TITLE
Roads and rivers are the same color as background layers

### ISSUE THREAD

**Issue by yanntanvez** [energy-data/market-opportunities#5]
![image](https://cloud.githubusercontent.com/assets/21108014/19078972/00643466-8a20-11e6-8296-5ec5e1f143ac.png)

**Comment by drewbo** [comment]
@yanntanvez can you describe more about the problem your seeing here?

**Comment by yanntanvez** [comment]
Hi and thanks drew.

Yes, when one activate the road layer as a background layer, the color of the roads is white, just like the rivers.

Thanks !
Yann

**Comment by drewbo** [comment]
@yanntanvez we aren't showing rivers here, only national/provincial boundaries which are sometimes tracking rivers. Roads are shown with a different thickness to differentiate them from the administrative boundaries

**Comment by yanntanvez** [comment]
@drewbo Thanks for the reply - then it could be useful to have the roads better differentiated from the boundaries. In the screenshot shared, it is very difficult to make the difference between one another. Maybe a latter fix. Not sure.

![image](https://cloud.githubusercontent.com/assets/21108014/19290275/f00b86ec-8fdc-11e6-8e5d-a9c483951e22.png)

**Comment by olafveerman** [comment]
@yanntanvez  We have addressed this by adding a dash to the country border:

![image](https://cloud.githubusercontent.com/assets/751330/19322102/c0353202-9085-11e6-9531-7494590914c2.png)
