### ISSUE TITLE
Population calculation

### ISSUE THREAD

**Issue by yanntanvez** [energy-data/market-opportunities#6]
Zambia total population is 14.5 million. When selecting the entire range we should have the full population but now looking at 11.5.

![image](https://cloud.githubusercontent.com/assets/21108014/19079638/47c549e2-8a22-11e6-91f3-e105f16fe776.png)

**Comment by drewbo** [comment]
@yanntanvez all our population estimates are from 2010 (the most recent continent level data from WorldPop) so they will underestimate the current values. In addition, I think we should emphasize that these are estimates that won't necessarily reflect exact values

**Comment by yanntanvez** [comment]
@drewbo Thanks. Zambia's population in 2010 was 13.2 million, compared to 14.5 million today. This is less than 10% error margin, which is big but acceptable. 
The difference between 14.5 (actual 2015) and 11.5 (which is what it represented in the app) is of 20%, which is huge, and too much of a variation for the revenue potential calculation. Please kindly double check and inform on how this could be addressed.

**Comment by drewbo** [comment]
The server calculation method will also address this discrepancy (it returns 13,169,572 for this geometry, within 1% of the 2010 numbers)

**Comment by yanntanvez** [comment]
Great ! Many thanks !!
